#!/bin/bash

set -e

help() {
  echo "Usage:"
  echo "  zmicro package install lima <args...>"
  echo ""
}

install() {
  # prepare vars
  local name="lima"
  # get system os/arch
  local arch="$(os::arch)"
  local os="Linux"
  # usr_bin_dir

  local user_lib_dir=/usr/lib
  local user_share_dir=/usr/share
  local usr_bin_dir=/usr/bin
  local tmp_dir="/tmp/$name"
  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./bin/*"

  if [ "$(os::is_macos)" = "true" ]; then
    os="Darwin"
    user_lib_dir=/usr/local/lib
    user_share_dir=/usr/local/share
    usr_bin_dir=/usr/local/bin

    if [ "$arch" = "amd64" ]; then
      arch="x86_64"
    elif [ "$arch" = "arm64" ]; then
      arch="arm64"
    else
      log::error "unknown architecture: $arch"
      exit 1
    fi
  else
    if [ "$arch" = "amd64" ]; then
      arch="x86_64"
    elif [ "$arch" = "arm64" ]; then
      arch="aarch64"
    else
      log::error "unknown architecture: $arch"
      exit 1
    fi
  fi

  if [ ! -d "$user_lib_dir" ]; then
    sudo mkdir -p $user_lib_dir
  fi

  if [ ! -d "$user_share_dir" ]; then
    sudo mkdir -p $user_share_dir
  fi

  if [ ! -d "$usr_bin_dir" ]; then
    sudo mkdir -p $usr_bin_dir
  fi

  # prepare context
  mkdir -p $tmp_dir
  cd $tmp_dir

  # reference: https://github.com/lima-vm/lima/releases
  # example:
  #   https://github.com/lima-vm/lima/releases/download/v0.12.0/lima-0.12.0-Darwin-arm64.tar.gz
  #   https://github.com/lima-vm/lima/releases/download/v0.12.0/lima-0.12.0-Darwin-x86_64.tar.gz
  # generate url
  local url="https://github.com/lima-vm/lima/releases/download/$PACKAGE_CORE_VERSION/${name}-${PACKAGE_CORE_VERSION#v}-${os}-${arch}.tar.gz"
  log::debug "[package][$name][$os][$arch] url: $url"

  # download
  os::curl --progress-bar -fSL $url -o $tmp_file

  # extract
  tar -zxvf $tmp_file >>/dev/null 2>&1
  rm -rf $tmp_file

  # install
  local lima_home=$user_lib_dir/lima
  if [ -d "$lima_home" ]; then
    sudo rm -rf $lima_home
  fi

  # lib
  sudo cp -rf $tmp_dir $lima_home
  # share'
  sudo ln -sf $lima_home/share/lima $user_share_dir/lima
  # bin
  sudo ln -sf $lima_home/bin/lima $usr_bin_dir/lima
  sudo ln -sf $lima_home/bin/limactl $usr_bin_dir/limactl
  sudo ln -sf $lima_home/bin/docker.lima $usr_bin_dir/docker.lima
  sudo ln -sf $lima_home/bin/podman.lima $usr_bin_dir/podman.lima
  sudo ln -sf $lima_home/bin/nerdctl.lima $usr_bin_dir/nerdctl.lima
  sudo ln -sf $lima_home/bin/apptainer.lima $usr_bin_dir/apptainer.lima

  # clean
  rm -rf $tmp_dir
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  install
  if [ $? -eq 0 ]; then
    log::success "install lima success."
    exit 0
  else
    log::error "install lima failed."
    exit 1
  fi
}

run() {
  core $@
}

run $@
